
server.port: 9601
server.servlet.session.timeout: 600s

spring:
  h2.console:
    enabled: true
    path: /h2

  datasource:
    url: jdbc:h2:file:~/recipe
    username: admin
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create