= Purchase List Frontend

(This project contains the sources of the purchase list service.)

== Available Scripts

In the project directory, you can run:

=== `npm start`

Runs the app in the development mode.

Open http://localhost:3000 to view it in the browser.

The page will reload if you make edits.

You will also see any lint errors in the console.

=== `npm test`

Launches the test runner in the interactive watch mode.

See the section about https://facebook.github.io/create-react-app/docs/running-tests[running tests] for more information.

=== `npm run build`

Builds the app for production to the `build` folder.<br>
It correctly bundles React in production mode and optimizes the build for the best performance.

The build is minified and the filenames include the hashes.<br>
Your app is ready to be deployed!

See the section about https://facebook.github.io/create-react-app/docs/deployment[deployment] for more information.

== Learn More

You can learn more in the https://facebook.github.io/create-react-app/docs/getting-started[Create React App documentation].

To learn React, check out the https://reactjs.org/[React documentation].

== Dependencies

.Runtime dependencies
[%header]
|===
| icon:sitemap[] Component | Version | Function | Website
| core-js | 2.5.7 | Polyfill of unimplemented Browser libraries | https://github.com/zloirock/core-js[Repository]
| jquery  | 3.3.1 | JQuery Ajax Library | https://jquery.com/[Website]
| lodash | 4.17.11 | Utility library | https://lodash.com/[Website]
| react | 16.6.3 | UI Rendering Library | https://reactjs.org/[Website]
| react-app-polyfill | 0.1.3 | Polyfills to get React running | https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill[Repository]
| react-dom | 16.6.3 | DOM modification library | https://reactjs.org/[Website]
| react-router-dom | 4.3.1 | Site transition library | https://www.npmjs.com/package/react-router-dom[NPM Package]
| react-scripts | 2.1.1 | Build Scripts | https://github.com/facebook/create-react-app[Repository]
| semantic-ui-css | 2.4.1 | Semantic UI CSS Framework | https://semantic-ui.com/[Website]
| semantic-ui-react | 0.83.0 | Semantic React Integration | https://react.semantic-ui.com/[Website]
|===

.Build time dependencies
[%header]
|===
| icon:sitemap[] Component | Version | Function | Website
| typescript | 3.1.6 | Typescript compiler | https://www.typescriptlang.org/[Website]
|===