
GET http://localhost:9603/api/kitchenDevices
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

###

GET http://localhost:9603/api/kitchenDevices/1
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

###

PUT http://localhost:9603/api/kitchenDevices/1
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{"name": "Test", "function":"Ffs fsk", "available": true}

###