= Selected the build system =
Matt Baumann <matthias.baumann@hsr,ch>
v1.0, November 18, 2018
:Author: Matt Baumann
:Email: matthias.baumann@hsr.ch
:Date: 18. November 2018
:Revision: Version 1.0
:icons: font
:y: icon:check[role="green"]
:n: icon:times[role="red"]

. Status: accepted
. Deciders: Matthias Baumann, Olaf Zimmermann
. Date: 2018-11-18

== Context and Problem Statement

We need to compose the data and the page fragments into a full UI. The composer must be able to integrate the data and
html snippets to an executable html file. This can happen on an backend server, a middleware or on the client itself.

The question is which Option shows the best characteristics in my criteria catalogue.

== Considered Options

I considered the following composition patterns:
* Portal Composition
* Backend Composition
* Middleware Composition
* Frontend Composition

== Decision Outcome

Chosen option: _option X_.

=== Negative consequences

* Composition makes the deployment harder and the infrastructure more complicated
* Builds are harder to manage, as they have cross-references

== Pros and Cons of the Options

=== Angular

https://angular.io/[Angular]

. {y} All needed components provided
. {y} Testing already prepared
. {y} Packaging system
. {y} Good separation of concerns
. {n} Performance
. {n} Hard to program (single HTTP GET involves HTTP Library, Reactive Streams, Dependency Injection)

===  React

https://reactjs.org/[React JS]

. {y} Productive programming
. {y} Good UI components
. {n} HTML in JS Files
- {n} Components not separable

=== Lucid JS with JQuery

https://jquery.com/[JQuery]

. {y} Performance
. {y} Understood by the students
. {n} Realistic example
. {n} Hard to setup
. {n} No UI Component library